<p>Formats scenarios columns of water balance for better display in charts.</p>

In [8]:
import pandas as pd

In [9]:
sspsrcp_labels =  ['Historical', 'SSP1-2.6', 'SSP2-4.5', 'SSP3-7.0', 'SSP5-8.5']
sspsrcp_values =  ['historical', 'ssp126', 'ssp245', 'ssp370', 'ssp585']
value_labels_dict = dict(zip(sspsrcp_values, sspsrcp_labels))

In [24]:
water_balance_csv_nuts = '/home/politti/data/Danube_5min/spei_nuts_2/water_balance_danube_nuts2.csv'
water_balance_csv_cru = '/home/politti/data/Danube_5min/spei_nuts_2/water_balance_danube_nuts2_cru.csv'

,oid,date,year,month,scenario,gcm,NUTS,NAME,NUTS0,water_balance
0,5.0,2015-01-31,2015,1,SSP3-7.0,GFDL-ESM4,AT11,Burgenland,AT,1.256848e+11
1,5.0,2015-02-28,2015,2,SSP3-7.0,GFDL-ESM4,AT11,Burgenland,AT,1.504878e+11
2,5.0,2015-03-31,2015,3,SSP3-7.0,GFDL-ESM4,AT11,Burgenland,AT,1.147553e+11
3,5.0,2015-04-30,2015,4,SSP3-7.0,GFDL-ESM4,AT11,Burgenland,AT,-1.653140e+11
4,5.0,2015-05-31,2015,5,SSP3-7.0,GFDL-ESM4,AT11,Burgenland,AT,-1.528005e+11

In [25]:
df = pd.read_csv(water_balance_csv_nuts)
#df['scenario'].unique()

# rename ssp-rcp for better charts display
df['scenario'] = df.scenario.replace(value_labels_dict)
#df['scenario'].unique()

# rename shapefile-object id column
df.rename(columns={'OBJECTID': 'nuts2_id'}, inplace=True)
df['nuts2_id'] = df['nuts2_id'].astype(int)

df.to_csv(water_balance_csv_nuts, index=False)
df.head(3)

,nuts2_id,date,year,month,scenario,gcm,NUTS,NAME,NUTS0,water_balance
0,5,2015-01-31,2015,1,SSP3-7.0,GFDL-ESM4,AT11,Burgenland,AT,1.256848e+11
1,5,2015-02-28,2015,2,SSP3-7.0,GFDL-ESM4,AT11,Burgenland,AT,1.504878e+11
2,5,2015-03-31,2015,3,SSP3-7.0,GFDL-ESM4,AT11,Burgenland,AT,1.147553e+11

In [26]:
df_cru = pd.read_csv(water_balance_csv_cru)
df_cru.rename(columns={'OBJECTID': 'nuts2_id'}, inplace=True)
df_cru['nuts2_id'] = df_cru['nuts2_id'].astype(int)
df_cru.to_csv(water_balance_csv_cru, index=False)
df_cru.head(3)

,nuts2_id,date,year,month,scenario,gcm,NUTS,NAME,NUTS0,water_balance
0,5,1951-01-16,1951,1,observed,cru,AT11,Burgenland,AT,1.200892e+11
1,5,1951-02-15,1951,2,observed,cru,AT11,Burgenland,AT,7.801337e+10
2,5,1951-03-16,1951,3,observed,cru,AT11,Burgenland,AT,1.916734e+11