<p>Formats scenarios columns of water balance for better display in charts.</p>

In [26]:
import pandas as pd

In [27]:
sspsrcp_labels =  ['Historical', 'SSP1-2.6', 'SSP2-4.5', 'SSP3-7.0', 'SSP5-8.5']
sspsrcp_values =  ['historical', 'ssp126', 'ssp245', 'ssp370', 'ssp585']
value_labels_dict = dict(zip(sspsrcp_values, sspsrcp_labels))

In [28]:
# water_balance_csv_nuts = '/home/politti/data/Danube_5min/spei_nuts_2/water_balance_danube_nuts2.csv'
# water_balance_csv_cru = '/home/politti/data/Danube_5min/spei_nuts_2/water_balance_danube_nuts2_cru.csv'

water_balance_csv_nuts = '/home/politti/data/Danube_5min/spei_nuts_2_1min/water_balance_danube_nuts2_1min.csv'
water_balance_csv_cru = '/home/politti/data/Danube_5min/spei_nuts_2_1min/water_balance_danube_nuts2_cru_1min.csv'

In [29]:
df = pd.read_csv(water_balance_csv_nuts)
#df['scenario'].unique()

# rename ssp-rcp for better charts display
df['scenario'] = df.scenario.replace(value_labels_dict)
#df['scenario'].unique()

# rename shapefile-object id column
df.rename(columns={'OBJECTID': 'nuts2_id'}, inplace=True)
df['nuts2_id'] = df['nuts2_id'].astype(int)

df.to_csv(water_balance_csv_nuts, index=False)
df.head(3)

,nuts2_id,date,year,month,scenario,gcm,NUTS,NAME,NUTS0,water_balance
0,5,1950-01-01,1950,1,Historical,GFDL-ESM4,AT11,Burgenland,AT,2.577695e+11
1,5,1950-02-01,1950,2,Historical,GFDL-ESM4,AT11,Burgenland,AT,2.381806e+10
2,5,1950-03-01,1950,3,Historical,GFDL-ESM4,AT11,Burgenland,AT,1.853798e+10

In [30]:
df_cru = pd.read_csv(water_balance_csv_cru)
df_cru.rename(columns={'OBJECTID': 'nuts2_id'}, inplace=True)
df_cru['nuts2_id'] = df_cru['nuts2_id'].astype(int)
df_cru.to_csv(water_balance_csv_cru, index=False)
df_cru.head(3)

,nuts2_id,date,year,month,scenario,gcm,NUTS,NAME,NUTS0,water_balance
0,5,1951-01-16,1951,1,observed,cru,AT11,Burgenland,AT,1.130304e+11
1,5,1951-02-15,1951,2,observed,cru,AT11,Burgenland,AT,7.333664e+10
2,5,1951-03-16,1951,3,observed,cru,AT11,Burgenland,AT,1.805102e+11