In [8]:
import geopandas as gpd
import pycountry
import pandas as pd

In [13]:
nuts_2_countries_shp = '/home/politti/data/Danube_baselayers/danube_nutw2_countries.shp'
gdf = gpd.read_file(nuts_2_countries_shp)
gdf.head()

  NUTS0  Country                                           geometry
0    RO  Romania  POLYGON ((28.11722 46.10696, 28.11839 46.10653...
1    HU  Hungary  POLYGON ((21.65981 47.02186, 21.66087 47.02143...
2    UA  Ukraine  MULTIPOLYGON (((28.98113 46.27727, 28.98899 46...
3    CZ     None  POLYGON ((15.33895 49.21994, 15.33912 49.2201,...
4    SI     None  MULTIPOLYGON (((14.09305 45.73075, 14.09274 45...

In [4]:
def get_country_info(iso2_code):
    try:
        # Look up the country object using the alpha_2 code
        country = pycountry.countries.get(alpha_2=iso2_code)
        # Return a tuple: (ISO3, Full Name)
        return country.alpha_3, country.name
    except (LookupError, AttributeError):
        # Return None for both if the code is invalid or missing
        return None, None

In [14]:
# 3. Apply the function and unpack into your two new columns
gdf[['ISO3', 'Country']] = gdf['NUTS0'].apply(
    lambda x: pd.Series(get_country_info(x))
)
gdf.rename(columns={'NUTS0': 'ISO2'}, inplace=True)
gdf = gdf[['ISO2', 'ISO3', 'Country', 'geometry']]
gdf.head(18)

,ISO2,ISO3,Country,geometry
0,RO,ROU,Romania,"POLYGON ((28.11722 46.10696, 28.11839 46.10653..."
1,HU,HUN,Hungary,"POLYGON ((21.65981 47.02186, 21.66087 47.02143..."
2,UA,UKR,Ukraine,"MULTIPOLYGON (((28.98113 46.27727, 28.98899 46..."
3,CZ,CZE,Czechia,"POLYGON ((15.33895 49.21994, 15.33912 49.2201,..."
4,SI,SVN,Slovenia,"MULTIPOLYGON (((14.09305 45.73075, 14.09274 45..."
5,RS,SRB,Serbia,"POLYGON ((22.50116 42.73929, 22.5008 42.73903,..."
6,MD,MDA,"Moldova, Republic of","POLYGON ((27.36089 48.44396, 27.3608 48.4436, ..."
7,ME,MNE,Montenegro,"POLYGON ((20.31872 42.83179, 20.31762 42.8332,..."
8,BA,BIH,Bosnia and Herzegovina,"MULTIPOLYGON (((19.42461 43.56697, 19.42462 43..."
9,SK,SVK,Slovakia,"POLYGON ((17.24675 48.01637, 17.24611 48.01843..."
10,DE,DEU,Germany,"MULTIPOLYGON (((10.09973 47.35501, 10.10004 47..."
11,BG,BGR,Bulgaria,"MULTIPOLYGON (((24.12217 42.77117, 24.12168 42..."
12,CH,CHE,Switzerland,"POLYGON ((10.46943 46.85487, 10.47036 46.85278..."
13,AT,AUT,Austria,"MULTIPOLYGON (((13.71198 46.52224, 13.71168 46..."
14,HR,HRV,Croatia,"MULTIPOLYGON (((14.49933 45.56662, 14.49977 45..."
15,XK,None,None,"MULTIPOLYGON (((20.08023 42.56144, 20.08122 42..."

In [17]:
gdf.to_file(nuts_2_countries_shp)